services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: translation-app-frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/src
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: translation-app-backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
