migration:
	go run migrations/migration.go
up:
	go run main.go
setup:
	go get -u gorm.io/gorm
	go get -u gorm.io/driver/postgres
	go get -u github.com/joho/godotenv
	go get -u github.com/dgrijalva/jwt-go
	go get -u github.com/gin-gonic/gin
	go get -u github.com/gin-contrib/cors